-- M2a: direct (one-to-one) conversations and durable messages.
-- migrate.js runs this whole file in one transaction, so it applies fully or not at all.
-- Group chats (type, name, owner) are added by a later migration in M3.

-- One row per conversation. A direct chat is identified by its pair of users.
create table chatty.conversations (
  id uuid primary key default gen_random_uuid(),
  -- "<smaller user id>:<larger user id>". The unique constraint is what guarantees one
  -- chat per pair, even when both users open it at the same moment (ON CONFLICT in the API).
  direct_key text not null unique
    check (direct_key ~ '^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}:[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$')
    -- Forces sorted order, so "b:a" can never become a second chat for "a:b",
    -- and rejects "a:a" (chatting with yourself), because a < a is false.
    -- COLLATE "C" compares bytes, the same order JavaScript's < uses for the API's sort;
    -- the default en_US collation may order punctuation differently.
    check (split_part(direct_key, ':', 1) < split_part(direct_key, ':', 2) collate "C"),
  -- Next message number for this chat. The send query locks this row (FOR UPDATE),
  -- reads it, inserts the message and increments it, so numbers have no gaps or repeats.
  -- integer (max ~2.1 billion per chat) keeps JSON numbers exact; bigint would not.
  next_seq integer not null default 1 check (next_seq > 0),
  created_at timestamptz not null default now()
);

-- Who belongs to which conversation. Every permission check goes through this table.
create table chatty.conversation_members (
  -- Removing a conversation or user removes the membership row (neither is deleted yet).
  conversation_id uuid not null references chatty.conversations (id) on delete cascade,
  user_id uuid not null references chatty.users (id) on delete cascade,
  joined_at timestamptz not null default now(),
  -- Highest message seq this member has read; unread counts arrive in M3.
  last_read_seq integer not null default 0 check (last_read_seq >= 0),
  -- The primary key also answers "is user X a member of conversation C?" quickly.
  primary key (conversation_id, user_id)
);
-- Reverse direction: "all conversations of user X" for the sidebar list.
create index conversation_members_user_id_idx
  on chatty.conversation_members (user_id, conversation_id);

-- Messages are append-only in this release (no edit/delete).
create table chatty.messages (
  id uuid primary key default gen_random_uuid(),
  conversation_id uuid not null references chatty.conversations (id) on delete cascade,
  -- No ON DELETE CASCADE: deleting a user must not silently erase other people's history.
  -- There is no account deletion yet, so the default (restrict) simply blocks it.
  -- shortcut: no index on sender_id; only a user delete would scan by it. Add
  -- "create index messages_sender_id_idx on chatty.messages (sender_id)" with account deletion.
  sender_id uuid not null references chatty.users (id),
  -- Generated by the browser before the first attempt and reused on every retry,
  -- so a retry after a lost response finds the existing row instead of inserting twice.
  client_message_id uuid not null,
  -- Position inside the conversation (1, 2, 3, ...), copied from conversations.next_seq.
  seq integer not null check (seq > 0),
  kind text not null default 'text' check (kind in ('text', 'gif')),
  -- char_length counts Unicode code points (an emoji is 1), matching messageBodyError.
  -- '\S' requires at least one non-whitespace character. For GIFs the body is the alt text.
  body text not null check (char_length(body) between 1 and 4000 and body ~ '\S'),
  -- Giphy id: letters/digits only, so it is safe to place inside a media URL.
  gif_id text check (gif_id ~ '^[A-Za-z0-9]+$'),
  -- GIF messages must have a gif_id and text messages must not.
  check ((kind = 'gif') = (gif_id is not null)),
  created_at timestamptz not null default now(),
  -- History reads "conversation C ordered by seq"; this unique index serves that query
  -- and makes a duplicate seq impossible even if application code had a bug.
  unique (conversation_id, seq),
  -- The idempotency key: one message per (chat, sender, client id). Scoped by sender,
  -- so another user reusing the same UUID value cannot collide with your message.
  unique (conversation_id, sender_id, client_message_id)
);

-- Same rule as 001: no implicit access for other database roles; the app connects as owner.
revoke all on chatty.conversations, chatty.conversation_members, chatty.messages from public;
