export const people = [
  {
    id: "me",
    name: "Alex Morgan",
    handle: "alex",
    avatar: "cat",
    online: true,
  },
  {
    id: "alice",
    name: "Alice Chen",
    handle: "alice",
    avatar: "fox",
    online: true,
  },
  {
    id: "marcus",
    name: "Marcus Reed",
    handle: "marcus",
    avatar: "raccoon",
    online: true,
  },
  {
    id: "sofia",
    name: "Sofia Patel",
    handle: "sofia",
    avatar: "owl",
    online: true,
  },
  {
    id: "jamie",
    name: "Jamie Park",
    handle: "jamie",
    avatar: "frog",
    online: false,
  },
  {
    id: "ben",
    name: "Ben Walker",
    handle: "ben",
    avatar: "bear",
    online: false,
  },
];
const msg = (id, author, text, time, status = "sent", extra = {}) => ({
  id,
  author,
  text,
  time,
  status,
  ...extra,
});
export const initialConversations = [
  {
    id: "workshop",
    name: "The workshop",
    type: "group",
    avatar: "forest",
    owner: "me",
    members: ["me", "alice", "marcus", "sofia"],
    unread: 2,
    time: "10:24",
    description:
      "A space for building things, breaking things, and figuring it out together.",
    olderLoaded: false,
    messages: [
      msg(
        "w1",
        "alice",
        "Morning team! The auth refactor is ready for a second pair of eyes.",
        "09:12",
      ),
      msg("w2", "alice", "Smaller diff this time. Promise.", "09:12"),
      msg(
        "w3",
        "marcus",
        "Just pulled it down. The token refresh looks much cleaner 👌",
        "09:16",
      ),
      msg(
        "w4",
        "me",
        "Nice! I fixed the race condition we spotted yesterday.\nThe retry now shares a single promise.",
        "09:18",
      ),
      msg("w5", "alice", "Here’s the key part:", "09:21"),
      msg(
        "w6",
        "alice",
        "const session = await refreshSession();",
        "09:21",
        "sent",
        { code: true },
      ),
      msg(
        "w7",
        "sofia",
        "That did it! Tested with a slow connection and everything holds up.",
        "10:03",
        "sent",
        { unreadStart: true },
      ),
      msg("w8", "sofia", "Are we still aiming for a Friday release?", "10:04"),
    ],
  },
  {
    id: "ship",
    name: "Ship it",
    type: "group",
    avatar: "rocket",
    owner: "alice",
    members: ["me", "alice", "jamie"],
    unread: 3,
    time: "09:14",
    description: "Small releases. Big high-fives.",
    olderLoaded: false,
    messages: [
      msg(
        "s1",
        "alice",
        "Release checklist is up. Can everyone give their area a quick smoke test?",
        "09:00",
      ),
      msg(
        "s2",
        "jamie",
        "I found a layout issue on mobile. Fix is in review.",
        "09:14",
        "sent",
        { unreadStart: true },
      ),
    ],
  },
  {
    id: "coffee",
    name: "Coffee & commits",
    type: "group",
    avatar: "coffee",
    owner: "me",
    members: ["me", "alice", "marcus", "sofia", "jamie"],
    unread: 0,
    time: "Yesterday",
    description: "The virtual kitchen. Bring a coffee and a good story.",
    olderLoaded: false,
    messages: [
      msg(
        "c1",
        "marcus",
        "Today’s debugging soundtrack: rain on the window and absolutely no meetings. ☕",
        "11:24",
      ),
      msg("c2", "me", "A very respectable development environment.", "11:26"),
    ],
  },
  ...["alice", "marcus", "sofia", "jamie"].map((id, i) => ({
    id,
    type: "direct",
    name: people.find((p) => p.id === id).name,
    avatar: people.find((p) => p.id === id).avatar,
    members: ["me", id],
    unread: [2, 1, 1, 0][i],
    time: ["10:22", "10:18", "10:03", "09:41"][i],
    olderLoaded: false,
    messages: [
      msg(
        `${id}1`,
        id,
        [
          "Hey! Could you take a look at the auth pull request?\nI left a note about the expired-token edge case.",
          "Just pushed the fix for that pesky race condition.",
          "The slow-network test passed! Here’s the reference I used: https://developer.mozilla.org/en-US/docs/Web/API/AbortController",
          "Sounds good! Let’s pair on it after lunch.",
        ][i],
        "09:30",
      ),
      msg(
        `${id}2`,
        "me",
        [
          "On it! Thanks for the clear reproduction steps.",
          "Nice work. I’ll review it this morning.",
          "Love a green test run. Thanks for checking it!",
          "Perfect, see you at 1.",
        ][i],
        "09:35",
      ),
      msg(
        `${id}3`,
        id,
        [
          "Are we still aiming for a Friday release?",
          "Just pulled it down.",
          "That did it! Tested with a slow connection.",
          "Sounds good!",
        ][i],
        ["10:22", "10:18", "10:03", "09:41"][i],
        "sent",
        { unreadStart: i < 3 },
      ),
    ],
  })),
];
export function olderMessages(chatId) {
  return Array.from({ length: 16 }, (_, i) =>
    msg(
      `${chatId}-old-${i}`,
      ["alice", "marcus", "me", "sofia"][i % 4],
      [
        "I can reproduce the issue when the connection drops mid-request.",
        "Good catch. Let’s keep the retry idempotent so we don’t insert the same message twice.",
        "Added a regression test. The draft survives switching conversations, too.",
        "Review is done. The smaller components make this much easier to follow.",
      ][i % 4],
      `${String(14 + Math.floor(i / 6)).padStart(2, "0")}:${String((i * 3) % 60).padStart(2, "0")}`,
      "sent",
      { older: true },
    ),
  );
}
